services:
  localboard:
    container_name: localboard
    image: golang:1.23-bookworm
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "27049:27049"
    command: make run
